import './globals.css'
import "bootstrap/dist/css/bootstrap.min.css"
import "font-awesome/css/font-awesome.css";
import 'material-icons/iconfont/material-icons.css';
import 'material-icons/iconfont/outlined.css';
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  // title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Toaster/>
    </html>
  )
}
